### ISSUE TITLE
Extension no longer seems to work

### ISSUE THREAD

**Issue by itsdevo** [zerobase/fb_hide_like_notifs#10]
It seems as if this extension no longer functions. I have  Mac OS Sierra, and Chrome Version 58.0.3029.110. I have tried reinstalling the extension but no luck. Will there be an update soon to fix this?

**Comment by zerobase** [comment]
Hmmm. Having same Sierra and Chrome 58.0, it still works fine for me. I can't reproduce the issue and fix it.

Sometimes Facebook delivers different versions of its software to arbitrary segments of users. It can explain why the problem happens to you and not to me. If the same issue comes to me, I can and will fix it.

Just in case, please check if you haven't disabled the extension.
chrome://extensions/
<img width="911" alt="screen shot 2017-05-31 at 15 26 40" src="https://cloud.githubusercontent.com/assets/1480739/26618520/98932c40-4615-11e7-97e6-7bea66c27e23.png">

**Comment by itsdevo** [comment]
Thank you for your reply. Yes, my extension is enabled, so I guess I have that different version of Facebook's software. :(  At least I now know why the problem is occurring, and hopefully if you do come across the issue in the future it will be resolved!Samantha

**Comment by itsdevo** [comment]
Again, thank you for giving me a theory behind the bug in the extension. Here's some additional information that might help you learn more about the bug: The little icon for Hide Like Notifs on my menu bar is gray (implying it is disabled however I have made sure it is marked as "enabled"). When I load the "all notifications" page on Facebook, it shows the "likes" as I mentioned  before. When I reload the page, the 'likes' are still there, but they are all marked as read. So the extension must be helping me a little bit :)

**Comment by zerobase** [comment]
Okay, I'll try to fix it. Thanks for your feedback! 😃

**Comment by zerobase** [comment]
fixed at v1.15.2 (6b73af0)
